# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  
  pull_request:
    branches: [ develop ]
  push:
    branches: [develop]
    

       

jobs:
 test:
   runs-on: ubuntu-latest
   steps:
    - id: time
      uses: nanzm/get-time-action@v1.1
      with:
         timeZone: 5.5
         format: 'YYYY-MM-DD-HH-mm-ss'
   outputs:
     Value: ${{github.event.repository.name }}.${{steps.time.outputs.time}}
 Test1:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: check version
        id: version
        run: echo "version is ${{needs.test.outputs.Value}}"
        
        
 Test2:
   runs-on: windows-latest
   steps:
    - name: Checkout private tools
      uses: actions/checkout@v2
      with:
       repository: mckesson/hvs-reporting-portal-veracode-reports

       token: ${{ secrets.API_TOKEN_GITHUB }} # `GitHub_PAT` is a secret that contains your PAT
       path: 'Veracode-file'
  
        

          
          
          
    
   

   
 
