# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
    

       

jobs:
 test:
   runs-on: ubuntu-latest
   steps:
    - id: time
      uses: nanzm/get-time-action@v1.1
      with:
         timeZone: 5.5
         format: 'YYYY-MM-DD-HH-mm-ss'
 Test1:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: check version
        id: version
        run: echo "version is ${{github.event.repository.name }}.${{needs.test.time.outputs.time}}"
        

          
          
          
    
   

   
 
